Revert "GHA: omit 3rd-party actions, reduce logged-in time, misc improvements (#102)"
This reverts commit 214368a2ed2ed450be888d81f8480f428c9bad29.

Due to:
```
1s
Run eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
WARNING: Image reference ghcr.io/curl/curl-container/curl-dev:master uses a tag, not a digest, to identify the image to sign.
    This can lead you to sign a different image than the intended one. Please use a
    digest (example.com/ubuntu@sha256:abc123...) rather than tag
    (example.com/ubuntu:latest) for the input to cosign. The ability to refer to
    images by tag will be removed in a future release.

Signing artifact...
Error: signing [ghcr.io/curl/curl-container/curl-dev:master]: recursively signing: signing digest: failed to upload layer: POST https://ghcr.io/v2/curl/curl-container/curl-dev/blobs/uploads/: UNAUTHORIZED: unauthenticated: User cannot be authenticated with the token provided.
error during command execution: signing [ghcr.io/curl/curl-container/curl-dev:master]: recursively signing: signing digest: failed to upload layer: POST https://ghcr.io/v2/curl/curl-container/curl-dev/blobs/uploads/: UNAUTHORIZED: unauthenticated: User cannot be authenticated with the token provided.
```
Ref: https://github.com/curl/curl-container/actions/runs/21273142636/job/61227326016